#!/bin/sh
#title       : cosmicbox
#description : starts cosmicbox system
#author      : rid
#date        : 16/03/2015
#version     : 0.0
#usage       : cosmicbox {start|stop|restart}
#--------------------------------------------------------------------------------

#
# Starts cosmibox
#

die () {
    echo "*** FATAL: $1"
    exit 1
}

COSMICBOX_HOME=/cosmicbox
COSMICBOX_HOSTNAME=$(cat /etc/hostname)
COSMICBOX_PID=/var/run/cosmicbox.pid

COSMICBOX_CONF=$COSMICBOX_HOME/cosmicbox.conf
COSMICBOX_ETC_DIR=$COSMICBOX_HOME/etc
COSMICBOX_TEMPLATES_DIR=$COSMICBOX_HOME/etc.templates
COSMICBOX_WWW_DIR=$COSMICBOX_HOME/www

# load config file
[ -f $COSMICBOX_CONF ] || die "Cannot find config file"
. $COSMICBOX_CONF

HOSTS_CONF=$COSMICBOX_ETC_DIR/hosts

DNSMASQ=/usr/sbin/dnsmasq
DNSMASQ_CONF=$COSMICBOX_ETC_DIR/dnsmasq.conf
DNSMASQ_PID=/var/run/dnsmasq.pid

HOSTAPD=/usr/sbin/hostapd
HOSTAPD_CONF=$COSMICBOX_ETC_DIR/hostapd.conf
HOSTAPD_PID=/var/run/hostapd.pid

TESTIFACE="cat /proc/net/dev | grep wlan0 > /dev/null"
TESTEDIMAX="lsusb -d 7392:7811 > /dev/null"

prepare_config() {

    # clear config directory
    rm -rf $COSMICBOX_ETC_DIR
    cp -rf $COSMICBOX_TEMPLATES_DIR $COSMICBOX_ETC_DIR

    # variables names (see cosmicbox.conf)
    # NOTE(rid): do not forget COSMICBOX_HOME, COSMICBOX_ETC_DIR and COSMICBOX_HOSTNAME vars
    CONFIG_VARS="COSMICBOX_HOME \
                 COSMICBOX_HOSTNAME \
                 COSMICBOX_ETC_DIR \
                 $(grep '^[[:blank:]]*[^[:blank:]=]\+[[:blank:]]*=' $COSMICBOX_CONF | cut -d= -f1 | sed 's/[[:blank:]]//g')"

    # complete every config file with variable from cosmicbox config file
    for f in $(find $COSMICBOX_ETC_DIR -type f); do

        for v in $CONFIG_VARS; do
            value=$(eval echo \$$v)
            # echo "$v ---> $value"
            sed -i 's|%'$v'%|'"$value"'|g' $f
        done

    done

}

start() {

    prepare_config

    # wait for usb key
    while [ ! -h /sys/block/sda ]; do
        sleep 1
    done

    fsck -c 850 -a /dev/sda1
    mount /dev/sda1

    # mount wlan0
    echo -n "Mounting wireless net interface wlan0: "
    if [ -n $COSMICBOX_WIFI_DEV_MODULE ]; then
        modprobe $COSMICBOX_WIFI_DEV_MODULE
    fi
    /sbin/ifconfig wlan0 $COSMICBOX_ADDR netmask $COSMICBOX_MASK up
    echo "OK"

    # start hostapd as daemon
    echo -n "Starting hostapd: "
    start-stop-daemon -S -b -q -m -p $HOSTAPD_PID --exec $HOSTAPD -- $HOSTAPD_CONF
    echo "OK"

    # start dnsmasq as daemon
    echo -n "Starting dnsmasq: "
    start-stop-daemon -S -q --exec $DNSMASQ -- -C $DNSMASQ_CONF
    echo "OK"

    # start nodejs (use forever)
    echo -n "Starting cosmicbox server..."
    start-stop-daemon -S -b -q -m -p $COSMICBOX_PID --exec node -- ${COSMICBOX_WWW_DIR}/app.js /media/usb0
    echo "OK"
}

stop() {

    # stop nodejs (use forever)
    echo -n "Stopping cosmicbox server..."
    start-stop-daemon -K -q -p $COSMICBOX_PID
    rm -f $COSMICBOX_PID
    echo "OK"

    # stop dnsmasq
    echo -n "Stopping dnsmasq: "
    start-stop-daemon -K -q -p $DNSMASQ_PID
    rm -f $DNSMASQ_PID
    echo "OK"

    # umount wifi interface
    echo "Unmounting wireless net interface wlan0: "
    /sbin/ifconfig wlan0 down
    if [ -n $COSMICBOX_WIFI_DEV_MODULE ]; then
        modprobe -r $COSMICBOX_WIFI_DEV_MODULE
    fi
    echo "OK"

    # stop hostapd
    echo -n "Stopping hostapd: "
    start-stop-daemon -K -q -p $HOSTAPD_PID
    rm -f $HOSTAPD_PID
    echo "OK"

    umount /dev/sda1
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

